"""Export the time series behind the figures as CSV and .mat.

IMPORTANT: these are outputs of the simplified Python models in this
folder (g10_model.py, freq_model.py, bus44_*_timing.py), NOT Simulink /
PSCAD results. They reproduce the figures exactly, but they must not be
reported as detailed-simulation data.
"""
import numpy as np
from scipy.io import savemat

import g10_model as gm
import freq_model as fm
import bus44_collapse_timing as bc
import bus44_voltage_timing as bw

NOTE = ("SYNTHETIC MODEL OUTPUT (Python reduced-order models in figures/), "
        "NOT Simulink results. Generated by export_data.py.")


def write(name, header_lines, cols):
    keys = list(cols)
    arr = np.column_stack([cols[k] for k in keys])
    with open(f"data/{name}.csv", "w") as fh:
        for line in [NOTE] + header_lines:
            fh.write(f"# {line}\n")
        fh.write(",".join(keys) + "\n")
        np.savetxt(fh, arr, delimiter=",", fmt="%.6g")
    savemat(f"data/{name}.mat", {**{k: np.asarray(v) for k, v in cols.items()},
                                 "note": NOTE,
                                 "description": " | ".join(header_lines)})
    print(f"data/{name}.csv/.mat  {arr.shape[0]} rows x {arr.shape[1]} cols")


# ---------------- Case T: rotor angles
gens = gm.stable_gens()
cols = {"time_s": gm.t,
        "G1_deg": gens["G1"], "G4_deg": gens["G4"], "G7_deg": gens["G7"],
        "G10_NC_deg": gm.g10("T")[0],
        "G10_CC_deg": gm.g10("CC")[0],
        "G10_PF_STATCOM_Tcomm0_deg": gm.g10("T", "STATCOM", 0.0)[0],
        "G10_PF_STATCOM_Tcomm200ms_deg": gm.g10("T", "STATCOM", 0.2)[0],
        "G10_PF_SVC_Tcomm0_deg": gm.g10("T", "SVC", 0.0)[0]}
q = gm.g10("T", "STATCOM", 0.0)[1]
cols["Q_STATCOM_Bus16_Tcomm0_Mvar"] = q
write("caseT_rotor_angles",
      ["Case T (G10 three-phase fault): onset 0.10 s, cleared 0.25 s",
       f"decision {gm.T_DEC:.4f} s; STATCOM full output {gm.T_ACT['STATCOM']:.4f} s;"
       f" SVC full output {gm.T_ACT['SVC']:.4f} s (+T_comm)",
       "angles are absolute rotor angles in degrees; dt = 1 ms"], cols)

# ---------------- Frequency case
runs = {k: fm.simulate(c, tc) for k, c, tc in
        [("NC", "NC", 0.0), ("CC", "CC", 0.0), ("PF_Tcomm0", "PF", 0.0),
         ("PF_Tcomm200ms", "PF", 0.2)]}
t = runs["NC"]["t"]
cols = {"time_s": t}
for k, r in runs.items():
    cols[f"f_{k}_Hz"] = r["f"]
for k, r in runs.items():
    cols[f"ROCOF_{k}_Hz_per_s"] = r["rocof"]
pf = runs["PF_Tcomm0"]
cols["BESS_Bus3_PF_Tcomm0_MW"] = pf["bess"]["Bus 3"]
cols["BESS_Bus29_PF_Tcomm0_MW"] = pf["bess"]["Bus 29"]
cols["BESS_total_PF_Tcomm0_MW"] = pf["bess"]["Bus 3"] + pf["bess"]["Bus 29"]
for g in ("G1", "G3", "G9", "G10", "G6"):
    cols[f"P_{g}_PF_Tcomm0_MW"] = pf["gen"][g]
cols["UFLS_shed_PF_Tcomm0_MW"] = pf["shed"]
write("frequency_case",
      ["G6 trip (650 MW) at 0.50 s, IEEE 39-bus High-RES, H_sys = 1.72 s",
       "NC = governor only; CC = governor + PI-AGC; PF = governor + AGC + "
       f"CNN-LSTM-dispatched BESS (dispatch {fm.T_DEC:.4f} s + T_comm, 250 MW/s)",
       "dt = 1 ms"], cols)

# ---------------- Bus 44 voltage case
cols = {"time_s": bc.t, "V_NC_pu": bc.v_nc, "V_CC_pu": bc.v_cc,
        "V_PF_Tcomm0_pu": bc.pf(bc.T_SVC),
        "V_PF_Tcomm200ms_pu": bc.pf(bc.T_SVC + 0.2)}
write("bus44_voltage_collapse_case",
      ["IEEE 118-bus Bus 44, line trip at 0.50 s, pre-disturbance 0.942 p.u.",
       f"PF = CNN-LSTM + SVC, full output at {bc.T_SVC:.4f} s (+T_comm)",
       "dt = 1 ms"], cols)

cols = {"time_s": bw.t, "V_SG_only_pu": bw.v_sg, "V_50RES_NC_pu": bw.v_nc,
        "V_50RES_PF_Tcomm0_pu": bw.cnn_lstm_svc(bw.T_SVC),
        "V_50RES_PF_Tcomm200ms_pu": bw.cnn_lstm_svc(bw.T_SVC + 0.2)}
write("bus44_voltage_wind_case",
      ["IEEE 118-bus Bus 44, line trip + wind variability at 0.50 s, "
       "pre-disturbance 0.942 p.u.", "noise-free curves; dt = 2 ms"], cols)
